spring:
  application:
    name: kampus-company
#####  DATASOURCE SETTINGS
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  datasource:
    driver-class-name: org.postgresql.Driver
      username: ${APP_DB_USER}
      password: ${APP_DB_PASSWORD}
      url: jdbc:postgresql://${APP_DB_HOSTNAME}:${APP_DB_PORT}/${APP_DB}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
#####  SECURITY SETTINGS
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST}:${KEYCLOAK_PORT}/realms/kampus
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties.mail:
        smtp:
          auth: true
          starttls.enable: true

bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}

server:
  port: ${APP_PORT}
  servlet:
    context-path: /v1

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html

logging:
  level:
    ROOT: INFO
    liquibase: INFO
    org.springframework:
      boot: INFO
      web: INFO